# Generated by Django 4.1.2 on 2022-12-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
