# Generated by Django 4.1.2 on 2022-12-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_remove_likes_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
