# Generated by Django 4.1.2 on 2022-11-13 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Active_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('base_price', models.IntegerField()),
                ('porpose_price', models.IntegerField()),
                ('image', models.CharField(max_length=50)),
                ('add_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
