# Generated by Django 4.1.2 on 2022-11-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='price',
            field=models.IntegerField(),
        ),
    ]
