# Generated by Django 4.1.2 on 2022-11-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_active_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='active_list',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='active_list',
            name='porpose_price',
            field=models.IntegerField(blank=True),
        ),
    ]
