# Generated by Django 4.1.2 on 2022-11-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_categorys_alter_active_list_porpose_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='active_list',
            name='category',
        ),
        migrations.AddField(
            model_name='categorys',
            name='active',
            field=models.ManyToManyField(blank=True, related_name='active', to='auctions.active_list'),
        ),
        migrations.AlterField(
            model_name='active_list',
            name='image',
            field=models.CharField(max_length=7000),
        ),
    ]
