# Generated by Django 4.1.2 on 2022-11-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_active_list_category_categorys_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorys',
            name='active',
        ),
        migrations.AddField(
            model_name='active_list',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='category', to='auctions.categorys'),
        ),
    ]
