# Generated by Django 4.1.2 on 2022-11-21 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_remove_categorys_active_active_list_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='active_list',
            name='category',
        ),
        migrations.AddField(
            model_name='active_list',
            name='category',
            field=models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, related_name='category', to='auctions.categorys'),
        ),
    ]
